### YamlMime:ManagedReference
items:
- uid: Reqnroll.Configuration.ReqnrollJsonLocator
  commentId: T:Reqnroll.Configuration.ReqnrollJsonLocator
  id: ReqnrollJsonLocator
  parent: Reqnroll.Configuration
  children:
  - Reqnroll.Configuration.ReqnrollJsonLocator.CompatibilityJsonConfigurationFileName
  - Reqnroll.Configuration.ReqnrollJsonLocator.GetReqnrollJsonFilePath
  - Reqnroll.Configuration.ReqnrollJsonLocator.JsonConfigurationFileName
  langs:
  - csharp
  - vb
  name: ReqnrollJsonLocator
  nameWithType: ReqnrollJsonLocator
  fullName: Reqnroll.Configuration.ReqnrollJsonLocator
  type: Class
  source:
    remote:
      path: Reqnroll/Configuration/ReqnrollJsonLocator.cs
      branch: main
      repo: git@github.com:reqnroll/Reqnroll.git
    id: ReqnrollJsonLocator
    path: ../Reqnroll/Reqnroll/Configuration/ReqnrollJsonLocator.cs
    startLine: 5
  assemblies:
  - Reqnroll
  namespace: Reqnroll.Configuration
  syntax:
    content: 'public class ReqnrollJsonLocator : IReqnrollJsonLocator'
    content.vb: Public Class ReqnrollJsonLocator Implements IReqnrollJsonLocator
  inheritance:
  - System.Object
  implements:
  - Reqnroll.Configuration.IReqnrollJsonLocator
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Reqnroll.Configuration.ReqnrollJsonLocator.JsonConfigurationFileName
  commentId: F:Reqnroll.Configuration.ReqnrollJsonLocator.JsonConfigurationFileName
  id: JsonConfigurationFileName
  parent: Reqnroll.Configuration.ReqnrollJsonLocator
  langs:
  - csharp
  - vb
  name: JsonConfigurationFileName
  nameWithType: ReqnrollJsonLocator.JsonConfigurationFileName
  fullName: Reqnroll.Configuration.ReqnrollJsonLocator.JsonConfigurationFileName
  type: Field
  source:
    remote:
      path: Reqnroll/Configuration/ReqnrollJsonLocator.cs
      branch: main
      repo: git@github.com:reqnroll/Reqnroll.git
    id: JsonConfigurationFileName
    path: ../Reqnroll/Reqnroll/Configuration/ReqnrollJsonLocator.cs
    startLine: 7
  assemblies:
  - Reqnroll
  namespace: Reqnroll.Configuration
  syntax:
    content: public const string JsonConfigurationFileName = "reqnroll.json"
    return:
      type: System.String
    content.vb: Public Const JsonConfigurationFileName As String = "reqnroll.json"
- uid: Reqnroll.Configuration.ReqnrollJsonLocator.CompatibilityJsonConfigurationFileName
  commentId: F:Reqnroll.Configuration.ReqnrollJsonLocator.CompatibilityJsonConfigurationFileName
  id: CompatibilityJsonConfigurationFileName
  parent: Reqnroll.Configuration.ReqnrollJsonLocator
  langs:
  - csharp
  - vb
  name: CompatibilityJsonConfigurationFileName
  nameWithType: ReqnrollJsonLocator.CompatibilityJsonConfigurationFileName
  fullName: Reqnroll.Configuration.ReqnrollJsonLocator.CompatibilityJsonConfigurationFileName
  type: Field
  source:
    remote:
      path: Reqnroll/Configuration/ReqnrollJsonLocator.cs
      branch: main
      repo: git@github.com:reqnroll/Reqnroll.git
    id: CompatibilityJsonConfigurationFileName
    path: ../Reqnroll/Reqnroll/Configuration/ReqnrollJsonLocator.cs
    startLine: 8
  assemblies:
  - Reqnroll
  namespace: Reqnroll.Configuration
  syntax:
    content: public const string CompatibilityJsonConfigurationFileName = "specflow.json"
    return:
      type: System.String
    content.vb: Public Const CompatibilityJsonConfigurationFileName As String = "specflow.json"
- uid: Reqnroll.Configuration.ReqnrollJsonLocator.GetReqnrollJsonFilePath
  commentId: M:Reqnroll.Configuration.ReqnrollJsonLocator.GetReqnrollJsonFilePath
  id: GetReqnrollJsonFilePath
  parent: Reqnroll.Configuration.ReqnrollJsonLocator
  langs:
  - csharp
  - vb
  name: GetReqnrollJsonFilePath()
  nameWithType: ReqnrollJsonLocator.GetReqnrollJsonFilePath()
  fullName: Reqnroll.Configuration.ReqnrollJsonLocator.GetReqnrollJsonFilePath()
  type: Method
  source:
    remote:
      path: Reqnroll/Configuration/ReqnrollJsonLocator.cs
      branch: main
      repo: git@github.com:reqnroll/Reqnroll.git
    id: GetReqnrollJsonFilePath
    path: ../Reqnroll/Reqnroll/Configuration/ReqnrollJsonLocator.cs
    startLine: 10
  assemblies:
  - Reqnroll
  namespace: Reqnroll.Configuration
  example: []
  syntax:
    content: public string GetReqnrollJsonFilePath()
    return:
      type: System.String
    content.vb: Public Function GetReqnrollJsonFilePath() As String
  overload: Reqnroll.Configuration.ReqnrollJsonLocator.GetReqnrollJsonFilePath*
  implements:
  - Reqnroll.Configuration.IReqnrollJsonLocator.GetReqnrollJsonFilePath
references:
- uid: Reqnroll.Configuration
  commentId: N:Reqnroll.Configuration
  href: Reqnroll.html
  name: Reqnroll.Configuration
  nameWithType: Reqnroll.Configuration
  fullName: Reqnroll.Configuration
  spec.csharp:
  - uid: Reqnroll
    name: Reqnroll
    href: Reqnroll.html
  - name: .
  - uid: Reqnroll.Configuration
    name: Configuration
    href: Reqnroll.Configuration.html
  spec.vb:
  - uid: Reqnroll
    name: Reqnroll
    href: Reqnroll.html
  - name: .
  - uid: Reqnroll.Configuration
    name: Configuration
    href: Reqnroll.Configuration.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Reqnroll.Configuration.IReqnrollJsonLocator
  commentId: T:Reqnroll.Configuration.IReqnrollJsonLocator
  parent: Reqnroll.Configuration
  href: Reqnroll.Configuration.IReqnrollJsonLocator.html
  name: IReqnrollJsonLocator
  nameWithType: IReqnrollJsonLocator
  fullName: Reqnroll.Configuration.IReqnrollJsonLocator
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Reqnroll.Configuration.ReqnrollJsonLocator.GetReqnrollJsonFilePath*
  commentId: Overload:Reqnroll.Configuration.ReqnrollJsonLocator.GetReqnrollJsonFilePath
  href: Reqnroll.Configuration.ReqnrollJsonLocator.html#Reqnroll_Configuration_ReqnrollJsonLocator_GetReqnrollJsonFilePath
  name: GetReqnrollJsonFilePath
  nameWithType: ReqnrollJsonLocator.GetReqnrollJsonFilePath
  fullName: Reqnroll.Configuration.ReqnrollJsonLocator.GetReqnrollJsonFilePath
- uid: Reqnroll.Configuration.IReqnrollJsonLocator.GetReqnrollJsonFilePath
  commentId: M:Reqnroll.Configuration.IReqnrollJsonLocator.GetReqnrollJsonFilePath
  parent: Reqnroll.Configuration.IReqnrollJsonLocator
  href: Reqnroll.Configuration.IReqnrollJsonLocator.html#Reqnroll_Configuration_IReqnrollJsonLocator_GetReqnrollJsonFilePath
  name: GetReqnrollJsonFilePath()
  nameWithType: IReqnrollJsonLocator.GetReqnrollJsonFilePath()
  fullName: Reqnroll.Configuration.IReqnrollJsonLocator.GetReqnrollJsonFilePath()
  spec.csharp:
  - uid: Reqnroll.Configuration.IReqnrollJsonLocator.GetReqnrollJsonFilePath
    name: GetReqnrollJsonFilePath
    href: Reqnroll.Configuration.IReqnrollJsonLocator.html#Reqnroll_Configuration_IReqnrollJsonLocator_GetReqnrollJsonFilePath
  - name: (
  - name: )
  spec.vb:
  - uid: Reqnroll.Configuration.IReqnrollJsonLocator.GetReqnrollJsonFilePath
    name: GetReqnrollJsonFilePath
    href: Reqnroll.Configuration.IReqnrollJsonLocator.html#Reqnroll_Configuration_IReqnrollJsonLocator_GetReqnrollJsonFilePath
  - name: (
  - name: )
