### YamlMime:ManagedReference
items:
- uid: Reqnroll.Configuration.JsonConfig.PluginElement
  commentId: T:Reqnroll.Configuration.JsonConfig.PluginElement
  id: PluginElement
  parent: Reqnroll.Configuration.JsonConfig
  children:
  - Reqnroll.Configuration.JsonConfig.PluginElement.Name
  - Reqnroll.Configuration.JsonConfig.PluginElement.Parameters
  - Reqnroll.Configuration.JsonConfig.PluginElement.Path
  - Reqnroll.Configuration.JsonConfig.PluginElement.Type
  langs:
  - csharp
  - vb
  name: PluginElement
  nameWithType: PluginElement
  fullName: Reqnroll.Configuration.JsonConfig.PluginElement
  type: Class
  source:
    remote:
      path: Reqnroll/Configuration/JsonConfig/PluginElement.cs
      branch: main
      repo: git@github.com:reqnroll/Reqnroll.git
    id: PluginElement
    path: ../Reqnroll/Reqnroll/Configuration/JsonConfig/PluginElement.cs
    startLine: 5
  assemblies:
  - Reqnroll
  namespace: Reqnroll.Configuration.JsonConfig
  syntax:
    content: public class PluginElement
    content.vb: Public Class PluginElement
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Reqnroll.Configuration.JsonConfig.PluginElement.Name
  commentId: P:Reqnroll.Configuration.JsonConfig.PluginElement.Name
  id: Name
  parent: Reqnroll.Configuration.JsonConfig.PluginElement
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: PluginElement.Name
  fullName: Reqnroll.Configuration.JsonConfig.PluginElement.Name
  type: Property
  source:
    remote:
      path: Reqnroll/Configuration/JsonConfig/PluginElement.cs
      branch: main
      repo: git@github.com:reqnroll/Reqnroll.git
    id: Name
    path: ../Reqnroll/Reqnroll/Configuration/JsonConfig/PluginElement.cs
    startLine: 7
  assemblies:
  - Reqnroll
  namespace: Reqnroll.Configuration.JsonConfig
  syntax:
    content: >-
      [JsonPropertyName("name")]

      public string Name { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <JsonPropertyName("name")>

      Public Property Name As String
  overload: Reqnroll.Configuration.JsonConfig.PluginElement.Name*
  attributes:
  - type: System.Text.Json.Serialization.JsonPropertyNameAttribute
    ctor: System.Text.Json.Serialization.JsonPropertyNameAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: name
- uid: Reqnroll.Configuration.JsonConfig.PluginElement.Path
  commentId: P:Reqnroll.Configuration.JsonConfig.PluginElement.Path
  id: Path
  parent: Reqnroll.Configuration.JsonConfig.PluginElement
  langs:
  - csharp
  - vb
  name: Path
  nameWithType: PluginElement.Path
  fullName: Reqnroll.Configuration.JsonConfig.PluginElement.Path
  type: Property
  source:
    remote:
      path: Reqnroll/Configuration/JsonConfig/PluginElement.cs
      branch: main
      repo: git@github.com:reqnroll/Reqnroll.git
    id: Path
    path: ../Reqnroll/Reqnroll/Configuration/JsonConfig/PluginElement.cs
    startLine: 10
  assemblies:
  - Reqnroll
  namespace: Reqnroll.Configuration.JsonConfig
  syntax:
    content: >-
      [JsonPropertyName("path")]

      public string Path { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <JsonPropertyName("path")>

      Public Property Path As String
  overload: Reqnroll.Configuration.JsonConfig.PluginElement.Path*
  attributes:
  - type: System.Text.Json.Serialization.JsonPropertyNameAttribute
    ctor: System.Text.Json.Serialization.JsonPropertyNameAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: path
- uid: Reqnroll.Configuration.JsonConfig.PluginElement.Parameters
  commentId: P:Reqnroll.Configuration.JsonConfig.PluginElement.Parameters
  id: Parameters
  parent: Reqnroll.Configuration.JsonConfig.PluginElement
  langs:
  - csharp
  - vb
  name: Parameters
  nameWithType: PluginElement.Parameters
  fullName: Reqnroll.Configuration.JsonConfig.PluginElement.Parameters
  type: Property
  source:
    remote:
      path: Reqnroll/Configuration/JsonConfig/PluginElement.cs
      branch: main
      repo: git@github.com:reqnroll/Reqnroll.git
    id: Parameters
    path: ../Reqnroll/Reqnroll/Configuration/JsonConfig/PluginElement.cs
    startLine: 13
  assemblies:
  - Reqnroll
  namespace: Reqnroll.Configuration.JsonConfig
  syntax:
    content: >-
      [JsonPropertyName("parameters")]

      public string Parameters { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <JsonPropertyName("parameters")>

      Public Property Parameters As String
  overload: Reqnroll.Configuration.JsonConfig.PluginElement.Parameters*
  attributes:
  - type: System.Text.Json.Serialization.JsonPropertyNameAttribute
    ctor: System.Text.Json.Serialization.JsonPropertyNameAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: parameters
- uid: Reqnroll.Configuration.JsonConfig.PluginElement.Type
  commentId: P:Reqnroll.Configuration.JsonConfig.PluginElement.Type
  id: Type
  parent: Reqnroll.Configuration.JsonConfig.PluginElement
  langs:
  - csharp
  - vb
  name: Type
  nameWithType: PluginElement.Type
  fullName: Reqnroll.Configuration.JsonConfig.PluginElement.Type
  type: Property
  source:
    remote:
      path: Reqnroll/Configuration/JsonConfig/PluginElement.cs
      branch: main
      repo: git@github.com:reqnroll/Reqnroll.git
    id: Type
    path: ../Reqnroll/Reqnroll/Configuration/JsonConfig/PluginElement.cs
    startLine: 16
  assemblies:
  - Reqnroll
  namespace: Reqnroll.Configuration.JsonConfig
  syntax:
    content: >-
      [JsonPropertyName("type")]

      public PluginType Type { get; set; }
    parameters: []
    return:
      type: Reqnroll.Plugins.PluginType
    content.vb: >-
      <JsonPropertyName("type")>

      Public Property Type As PluginType
  overload: Reqnroll.Configuration.JsonConfig.PluginElement.Type*
  attributes:
  - type: System.Text.Json.Serialization.JsonPropertyNameAttribute
    ctor: System.Text.Json.Serialization.JsonPropertyNameAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: type
references:
- uid: Reqnroll.Configuration.JsonConfig
  commentId: N:Reqnroll.Configuration.JsonConfig
  href: Reqnroll.html
  name: Reqnroll.Configuration.JsonConfig
  nameWithType: Reqnroll.Configuration.JsonConfig
  fullName: Reqnroll.Configuration.JsonConfig
  spec.csharp:
  - uid: Reqnroll
    name: Reqnroll
    href: Reqnroll.html
  - name: .
  - uid: Reqnroll.Configuration
    name: Configuration
    href: Reqnroll.Configuration.html
  - name: .
  - uid: Reqnroll.Configuration.JsonConfig
    name: JsonConfig
    href: Reqnroll.Configuration.JsonConfig.html
  spec.vb:
  - uid: Reqnroll
    name: Reqnroll
    href: Reqnroll.html
  - name: .
  - uid: Reqnroll.Configuration
    name: Configuration
    href: Reqnroll.Configuration.html
  - name: .
  - uid: Reqnroll.Configuration.JsonConfig
    name: JsonConfig
    href: Reqnroll.Configuration.JsonConfig.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Reqnroll.Configuration.JsonConfig.PluginElement.Name*
  commentId: Overload:Reqnroll.Configuration.JsonConfig.PluginElement.Name
  href: Reqnroll.Configuration.JsonConfig.PluginElement.html#Reqnroll_Configuration_JsonConfig_PluginElement_Name
  name: Name
  nameWithType: PluginElement.Name
  fullName: Reqnroll.Configuration.JsonConfig.PluginElement.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Reqnroll.Configuration.JsonConfig.PluginElement.Path*
  commentId: Overload:Reqnroll.Configuration.JsonConfig.PluginElement.Path
  href: Reqnroll.Configuration.JsonConfig.PluginElement.html#Reqnroll_Configuration_JsonConfig_PluginElement_Path
  name: Path
  nameWithType: PluginElement.Path
  fullName: Reqnroll.Configuration.JsonConfig.PluginElement.Path
- uid: Reqnroll.Configuration.JsonConfig.PluginElement.Parameters*
  commentId: Overload:Reqnroll.Configuration.JsonConfig.PluginElement.Parameters
  href: Reqnroll.Configuration.JsonConfig.PluginElement.html#Reqnroll_Configuration_JsonConfig_PluginElement_Parameters
  name: Parameters
  nameWithType: PluginElement.Parameters
  fullName: Reqnroll.Configuration.JsonConfig.PluginElement.Parameters
- uid: Reqnroll.Configuration.JsonConfig.PluginElement.Type*
  commentId: Overload:Reqnroll.Configuration.JsonConfig.PluginElement.Type
  href: Reqnroll.Configuration.JsonConfig.PluginElement.html#Reqnroll_Configuration_JsonConfig_PluginElement_Type
  name: Type
  nameWithType: PluginElement.Type
  fullName: Reqnroll.Configuration.JsonConfig.PluginElement.Type
- uid: Reqnroll.Plugins.PluginType
  commentId: T:Reqnroll.Plugins.PluginType
  parent: Reqnroll.Plugins
  href: Reqnroll.Plugins.PluginType.html
  name: PluginType
  nameWithType: PluginType
  fullName: Reqnroll.Plugins.PluginType
- uid: Reqnroll.Plugins
  commentId: N:Reqnroll.Plugins
  href: Reqnroll.html
  name: Reqnroll.Plugins
  nameWithType: Reqnroll.Plugins
  fullName: Reqnroll.Plugins
  spec.csharp:
  - uid: Reqnroll
    name: Reqnroll
    href: Reqnroll.html
  - name: .
  - uid: Reqnroll.Plugins
    name: Plugins
    href: Reqnroll.Plugins.html
  spec.vb:
  - uid: Reqnroll
    name: Reqnroll
    href: Reqnroll.html
  - name: .
  - uid: Reqnroll.Plugins
    name: Plugins
    href: Reqnroll.Plugins.html
