### YamlMime:ManagedReference
items:
- uid: Reqnroll.Configuration.JsonConfig.Dependency
  commentId: T:Reqnroll.Configuration.JsonConfig.Dependency
  id: Dependency
  parent: Reqnroll.Configuration.JsonConfig
  children:
  - Reqnroll.Configuration.JsonConfig.Dependency.ImplementationType
  - Reqnroll.Configuration.JsonConfig.Dependency.InterfaceType
  - Reqnroll.Configuration.JsonConfig.Dependency.Name
  langs:
  - csharp
  - vb
  name: Dependency
  nameWithType: Dependency
  fullName: Reqnroll.Configuration.JsonConfig.Dependency
  type: Class
  source:
    remote:
      path: Reqnroll/Configuration/JsonConfig/Dependency.cs
      branch: main
      repo: git@github.com:reqnroll/Reqnroll.git
    id: Dependency
    path: ../Reqnroll/Reqnroll/Configuration/JsonConfig/Dependency.cs
    startLine: 4
  assemblies:
  - Reqnroll
  namespace: Reqnroll.Configuration.JsonConfig
  syntax:
    content: public class Dependency
    content.vb: Public Class Dependency
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Reqnroll.Configuration.JsonConfig.Dependency.ImplementationType
  commentId: P:Reqnroll.Configuration.JsonConfig.Dependency.ImplementationType
  id: ImplementationType
  parent: Reqnroll.Configuration.JsonConfig.Dependency
  langs:
  - csharp
  - vb
  name: ImplementationType
  nameWithType: Dependency.ImplementationType
  fullName: Reqnroll.Configuration.JsonConfig.Dependency.ImplementationType
  type: Property
  source:
    remote:
      path: Reqnroll/Configuration/JsonConfig/Dependency.cs
      branch: main
      repo: git@github.com:reqnroll/Reqnroll.git
    id: ImplementationType
    path: ../Reqnroll/Reqnroll/Configuration/JsonConfig/Dependency.cs
    startLine: 6
  assemblies:
  - Reqnroll
  namespace: Reqnroll.Configuration.JsonConfig
  syntax:
    content: >-
      [JsonPropertyName("type")]

      public string ImplementationType { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <JsonPropertyName("type")>

      Public Property ImplementationType As String
  overload: Reqnroll.Configuration.JsonConfig.Dependency.ImplementationType*
  attributes:
  - type: System.Text.Json.Serialization.JsonPropertyNameAttribute
    ctor: System.Text.Json.Serialization.JsonPropertyNameAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: type
- uid: Reqnroll.Configuration.JsonConfig.Dependency.InterfaceType
  commentId: P:Reqnroll.Configuration.JsonConfig.Dependency.InterfaceType
  id: InterfaceType
  parent: Reqnroll.Configuration.JsonConfig.Dependency
  langs:
  - csharp
  - vb
  name: InterfaceType
  nameWithType: Dependency.InterfaceType
  fullName: Reqnroll.Configuration.JsonConfig.Dependency.InterfaceType
  type: Property
  source:
    remote:
      path: Reqnroll/Configuration/JsonConfig/Dependency.cs
      branch: main
      repo: git@github.com:reqnroll/Reqnroll.git
    id: InterfaceType
    path: ../Reqnroll/Reqnroll/Configuration/JsonConfig/Dependency.cs
    startLine: 8
  assemblies:
  - Reqnroll
  namespace: Reqnroll.Configuration.JsonConfig
  syntax:
    content: >-
      [JsonPropertyName("as")]

      public string InterfaceType { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <JsonPropertyName("as")>

      Public Property InterfaceType As String
  overload: Reqnroll.Configuration.JsonConfig.Dependency.InterfaceType*
  attributes:
  - type: System.Text.Json.Serialization.JsonPropertyNameAttribute
    ctor: System.Text.Json.Serialization.JsonPropertyNameAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: as
- uid: Reqnroll.Configuration.JsonConfig.Dependency.Name
  commentId: P:Reqnroll.Configuration.JsonConfig.Dependency.Name
  id: Name
  parent: Reqnroll.Configuration.JsonConfig.Dependency
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: Dependency.Name
  fullName: Reqnroll.Configuration.JsonConfig.Dependency.Name
  type: Property
  source:
    remote:
      path: Reqnroll/Configuration/JsonConfig/Dependency.cs
      branch: main
      repo: git@github.com:reqnroll/Reqnroll.git
    id: Name
    path: ../Reqnroll/Reqnroll/Configuration/JsonConfig/Dependency.cs
    startLine: 10
  assemblies:
  - Reqnroll
  namespace: Reqnroll.Configuration.JsonConfig
  syntax:
    content: >-
      [JsonPropertyName("name")]

      public string Name { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <JsonPropertyName("name")>

      Public Property Name As String
  overload: Reqnroll.Configuration.JsonConfig.Dependency.Name*
  attributes:
  - type: System.Text.Json.Serialization.JsonPropertyNameAttribute
    ctor: System.Text.Json.Serialization.JsonPropertyNameAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: name
references:
- uid: Reqnroll.Configuration.JsonConfig
  commentId: N:Reqnroll.Configuration.JsonConfig
  href: Reqnroll.html
  name: Reqnroll.Configuration.JsonConfig
  nameWithType: Reqnroll.Configuration.JsonConfig
  fullName: Reqnroll.Configuration.JsonConfig
  spec.csharp:
  - uid: Reqnroll
    name: Reqnroll
    href: Reqnroll.html
  - name: .
  - uid: Reqnroll.Configuration
    name: Configuration
    href: Reqnroll.Configuration.html
  - name: .
  - uid: Reqnroll.Configuration.JsonConfig
    name: JsonConfig
    href: Reqnroll.Configuration.JsonConfig.html
  spec.vb:
  - uid: Reqnroll
    name: Reqnroll
    href: Reqnroll.html
  - name: .
  - uid: Reqnroll.Configuration
    name: Configuration
    href: Reqnroll.Configuration.html
  - name: .
  - uid: Reqnroll.Configuration.JsonConfig
    name: JsonConfig
    href: Reqnroll.Configuration.JsonConfig.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Reqnroll.Configuration.JsonConfig.Dependency.ImplementationType*
  commentId: Overload:Reqnroll.Configuration.JsonConfig.Dependency.ImplementationType
  href: Reqnroll.Configuration.JsonConfig.Dependency.html#Reqnroll_Configuration_JsonConfig_Dependency_ImplementationType
  name: ImplementationType
  nameWithType: Dependency.ImplementationType
  fullName: Reqnroll.Configuration.JsonConfig.Dependency.ImplementationType
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Reqnroll.Configuration.JsonConfig.Dependency.InterfaceType*
  commentId: Overload:Reqnroll.Configuration.JsonConfig.Dependency.InterfaceType
  href: Reqnroll.Configuration.JsonConfig.Dependency.html#Reqnroll_Configuration_JsonConfig_Dependency_InterfaceType
  name: InterfaceType
  nameWithType: Dependency.InterfaceType
  fullName: Reqnroll.Configuration.JsonConfig.Dependency.InterfaceType
- uid: Reqnroll.Configuration.JsonConfig.Dependency.Name*
  commentId: Overload:Reqnroll.Configuration.JsonConfig.Dependency.Name
  href: Reqnroll.Configuration.JsonConfig.Dependency.html#Reqnroll_Configuration_JsonConfig_Dependency_Name
  name: Name
  nameWithType: Dependency.Name
  fullName: Reqnroll.Configuration.JsonConfig.Dependency.Name
