### YamlMime:ManagedReference
items:
- uid: Reqnroll.UnitTestProvider.UnitTestProviderConfiguration
  commentId: T:Reqnroll.UnitTestProvider.UnitTestProviderConfiguration
  id: UnitTestProviderConfiguration
  parent: Reqnroll.UnitTestProvider
  children:
  - Reqnroll.UnitTestProvider.UnitTestProviderConfiguration.UnitTestProvider
  - Reqnroll.UnitTestProvider.UnitTestProviderConfiguration.UseUnitTestProvider(System.String)
  langs:
  - csharp
  - vb
  name: UnitTestProviderConfiguration
  nameWithType: UnitTestProviderConfiguration
  fullName: Reqnroll.UnitTestProvider.UnitTestProviderConfiguration
  type: Class
  source:
    remote:
      path: Reqnroll/UnitTestProvider/UnitTestProviderConfiguration.cs
      branch: main
      repo: git@github.com:reqnroll/Reqnroll.git
    id: UnitTestProviderConfiguration
    path: ../Reqnroll/Reqnroll/UnitTestProvider/UnitTestProviderConfiguration.cs
    startLine: 4
  assemblies:
  - Reqnroll
  namespace: Reqnroll.UnitTestProvider
  syntax:
    content: public class UnitTestProviderConfiguration
    content.vb: Public Class UnitTestProviderConfiguration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Reqnroll.UnitTestProvider.UnitTestProviderConfiguration.UseUnitTestProvider(System.String)
  commentId: M:Reqnroll.UnitTestProvider.UnitTestProviderConfiguration.UseUnitTestProvider(System.String)
  id: UseUnitTestProvider(System.String)
  parent: Reqnroll.UnitTestProvider.UnitTestProviderConfiguration
  langs:
  - csharp
  - vb
  name: UseUnitTestProvider(string)
  nameWithType: UnitTestProviderConfiguration.UseUnitTestProvider(string)
  fullName: Reqnroll.UnitTestProvider.UnitTestProviderConfiguration.UseUnitTestProvider(string)
  type: Method
  source:
    remote:
      path: Reqnroll/UnitTestProvider/UnitTestProviderConfiguration.cs
      branch: main
      repo: git@github.com:reqnroll/Reqnroll.git
    id: UseUnitTestProvider
    path: ../Reqnroll/Reqnroll/UnitTestProvider/UnitTestProviderConfiguration.cs
    startLine: 6
  assemblies:
  - Reqnroll
  namespace: Reqnroll.UnitTestProvider
  syntax:
    content: public void UseUnitTestProvider(string unitTestProviderName)
    parameters:
    - id: unitTestProviderName
      type: System.String
    content.vb: Public Sub UseUnitTestProvider(unitTestProviderName As String)
  overload: Reqnroll.UnitTestProvider.UnitTestProviderConfiguration.UseUnitTestProvider*
  nameWithType.vb: UnitTestProviderConfiguration.UseUnitTestProvider(String)
  fullName.vb: Reqnroll.UnitTestProvider.UnitTestProviderConfiguration.UseUnitTestProvider(String)
  name.vb: UseUnitTestProvider(String)
- uid: Reqnroll.UnitTestProvider.UnitTestProviderConfiguration.UnitTestProvider
  commentId: P:Reqnroll.UnitTestProvider.UnitTestProviderConfiguration.UnitTestProvider
  id: UnitTestProvider
  parent: Reqnroll.UnitTestProvider.UnitTestProviderConfiguration
  langs:
  - csharp
  - vb
  name: UnitTestProvider
  nameWithType: UnitTestProviderConfiguration.UnitTestProvider
  fullName: Reqnroll.UnitTestProvider.UnitTestProviderConfiguration.UnitTestProvider
  type: Property
  source:
    remote:
      path: Reqnroll/UnitTestProvider/UnitTestProviderConfiguration.cs
      branch: main
      repo: git@github.com:reqnroll/Reqnroll.git
    id: UnitTestProvider
    path: ../Reqnroll/Reqnroll/UnitTestProvider/UnitTestProviderConfiguration.cs
    startLine: 17
  assemblies:
  - Reqnroll
  namespace: Reqnroll.UnitTestProvider
  syntax:
    content: public string UnitTestProvider { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property UnitTestProvider As String
  overload: Reqnroll.UnitTestProvider.UnitTestProviderConfiguration.UnitTestProvider*
references:
- uid: Reqnroll.UnitTestProvider
  commentId: N:Reqnroll.UnitTestProvider
  href: Reqnroll.html
  name: Reqnroll.UnitTestProvider
  nameWithType: Reqnroll.UnitTestProvider
  fullName: Reqnroll.UnitTestProvider
  spec.csharp:
  - uid: Reqnroll
    name: Reqnroll
    href: Reqnroll.html
  - name: .
  - uid: Reqnroll.UnitTestProvider
    name: UnitTestProvider
    href: Reqnroll.UnitTestProvider.html
  spec.vb:
  - uid: Reqnroll
    name: Reqnroll
    href: Reqnroll.html
  - name: .
  - uid: Reqnroll.UnitTestProvider
    name: UnitTestProvider
    href: Reqnroll.UnitTestProvider.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Reqnroll.UnitTestProvider.UnitTestProviderConfiguration.UseUnitTestProvider*
  commentId: Overload:Reqnroll.UnitTestProvider.UnitTestProviderConfiguration.UseUnitTestProvider
  href: Reqnroll.UnitTestProvider.UnitTestProviderConfiguration.html#Reqnroll_UnitTestProvider_UnitTestProviderConfiguration_UseUnitTestProvider_System_String_
  name: UseUnitTestProvider
  nameWithType: UnitTestProviderConfiguration.UseUnitTestProvider
  fullName: Reqnroll.UnitTestProvider.UnitTestProviderConfiguration.UseUnitTestProvider
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Reqnroll.UnitTestProvider.UnitTestProviderConfiguration.UnitTestProvider*
  commentId: Overload:Reqnroll.UnitTestProvider.UnitTestProviderConfiguration.UnitTestProvider
  href: Reqnroll.UnitTestProvider.UnitTestProviderConfiguration.html#Reqnroll_UnitTestProvider_UnitTestProviderConfiguration_UnitTestProvider
  name: UnitTestProvider
  nameWithType: UnitTestProviderConfiguration.UnitTestProvider
  fullName: Reqnroll.UnitTestProvider.UnitTestProviderConfiguration.UnitTestProvider
