### YamlMime:ManagedReference
items:
- uid: Reqnroll.TestFramework.ITestRunSettingsProvider
  commentId: T:Reqnroll.TestFramework.ITestRunSettingsProvider
  id: ITestRunSettingsProvider
  parent: Reqnroll.TestFramework
  children:
  - Reqnroll.TestFramework.ITestRunSettingsProvider.GetTestDirectory
  langs:
  - csharp
  - vb
  name: ITestRunSettingsProvider
  nameWithType: ITestRunSettingsProvider
  fullName: Reqnroll.TestFramework.ITestRunSettingsProvider
  type: Interface
  source:
    remote:
      path: Reqnroll/TestFramework/ITestRunSettingsProvider.cs
      branch: main
      repo: git@github.com:reqnroll/Reqnroll.git
    id: ITestRunSettingsProvider
    path: ../Reqnroll/Reqnroll/TestFramework/ITestRunSettingsProvider.cs
    startLine: 2
  assemblies:
  - Reqnroll
  namespace: Reqnroll.TestFramework
  syntax:
    content: public interface ITestRunSettingsProvider
    content.vb: Public Interface ITestRunSettingsProvider
- uid: Reqnroll.TestFramework.ITestRunSettingsProvider.GetTestDirectory
  commentId: M:Reqnroll.TestFramework.ITestRunSettingsProvider.GetTestDirectory
  id: GetTestDirectory
  parent: Reqnroll.TestFramework.ITestRunSettingsProvider
  langs:
  - csharp
  - vb
  name: GetTestDirectory()
  nameWithType: ITestRunSettingsProvider.GetTestDirectory()
  fullName: Reqnroll.TestFramework.ITestRunSettingsProvider.GetTestDirectory()
  type: Method
  source:
    remote:
      path: Reqnroll/TestFramework/ITestRunSettingsProvider.cs
      branch: main
      repo: git@github.com:reqnroll/Reqnroll.git
    id: GetTestDirectory
    path: ../Reqnroll/Reqnroll/TestFramework/ITestRunSettingsProvider.cs
    startLine: 4
  assemblies:
  - Reqnroll
  namespace: Reqnroll.TestFramework
  syntax:
    content: string GetTestDirectory()
    return:
      type: System.String
    content.vb: Function GetTestDirectory() As String
  overload: Reqnroll.TestFramework.ITestRunSettingsProvider.GetTestDirectory*
references:
- uid: Reqnroll.TestFramework
  commentId: N:Reqnroll.TestFramework
  href: Reqnroll.html
  name: Reqnroll.TestFramework
  nameWithType: Reqnroll.TestFramework
  fullName: Reqnroll.TestFramework
  spec.csharp:
  - uid: Reqnroll
    name: Reqnroll
    href: Reqnroll.html
  - name: .
  - uid: Reqnroll.TestFramework
    name: TestFramework
    href: Reqnroll.TestFramework.html
  spec.vb:
  - uid: Reqnroll
    name: Reqnroll
    href: Reqnroll.html
  - name: .
  - uid: Reqnroll.TestFramework
    name: TestFramework
    href: Reqnroll.TestFramework.html
- uid: Reqnroll.TestFramework.ITestRunSettingsProvider.GetTestDirectory*
  commentId: Overload:Reqnroll.TestFramework.ITestRunSettingsProvider.GetTestDirectory
  href: Reqnroll.TestFramework.ITestRunSettingsProvider.html#Reqnroll_TestFramework_ITestRunSettingsProvider_GetTestDirectory
  name: GetTestDirectory
  nameWithType: ITestRunSettingsProvider.GetTestDirectory
  fullName: Reqnroll.TestFramework.ITestRunSettingsProvider.GetTestDirectory
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
